### ISSUE TITLE
Calling functions from workflow with multiple arguments

### ISSUE THREAD

**Issue by ymer** [mailund/gwf#96] opened 2016-08-06 09:51 UTC
This is perhaps not an issue with the gwf code, but more a question about usage.

I am often in the situation that a custom script needs a very large number of files as input (infiles). And I am highly in doubt about how best to do this with the workflow. The problem is that the list of infiles is needed both by the workflow and the script, and how best to communicate between the two.

Some options:

1 - Pass the infiles as an argument in a long, comma-seperated list.

Example:
'''python do_something.py file_1,file_2,file_3,...,file_n'''

This avoids code duplication, but it doesn't seem neat to have extremely long script calls.

2 - Pass an argument that when given as input to a function will give all the infiles as output.

This gives short script calls, but means that there must be a function that processes this argument, which is present both in the workflow and in the script that is called.

3 - Write a file that contains all the infiles. Pass an argument with the path to this file. Read this file from the script.

I wonder if you have any thoughts about which solution is preferable, and if there are other solutions I haven't thought of.

**Comment by mailund** [comment] 2016-08-06 10:07
This is easily done if you use functions instead of the template function. It was to solve this problem I added that functionality

**Comment by ymer** [comment] 2016-08-06 10:45
I assume you are referring to this example in the documentation:

  shell_spec = '''

  samtools merge - {inputbams} | samtools rmdup -s - {name}.bam

  '''.format(inputbams = ' '.join(inputfiles), name=individual)


This is solution 1 above, as I understand it. The script call can potentially be extremely large, since all the inputfile names are in it. But maybe this is not something I should worry about.

**Comment by ymer** [comment] 2016-08-06 11:06
xargs show limits
Maximum length of command we could actually use: 2611778

I think this means it is something I should worry about.

**Comment by mailund** [comment] 2016-08-06 11:18
That is an OS issue. There is a limit to how large a command-line you can execute. That is not something we can easily solve in a target; you will need some other way to provide the arguments if you run into that problem.

**Comment by dansondergaard** [comment] 2016-08-08 12:39
I'll close this issue since the problem is not related to gwf.

**Closed by dansondergaard** 2016-08-08 12:39 UTC
Labels: question
