### ISSUE TITLE
Should gwf workers start as a daemon process?

### ISSUE THREAD

**Issue by mailund** [mailund/gwf#158] opened 2017-05-12 08:41 UTC
Instead of having `gwf workers` start and not terminate, would it make sense to have commands

```sh
gwf workers start
```

and

```sh
gwf workes stop
```

processes that starts and stop daemon processes?

**Comment by dansondergaard** [comment] 2017-05-12 23:47
I guess this is a dupe of #121. I'm not sure that I think it's a "safe" idea since users could end up having a ton of workers running, listening on different ports. At least it would require a "gwf workers list" too, to show all running worker pools.

Also, I'd like to figure out how to actually test the workers before expanding more on the implementation.

**Comment by dansondergaard** [comment] 2017-05-16 04:24
Closing since this is a dupe of #121.

**Closed by dansondergaard** 2017-05-16 04:24 UTC
